### ISSUE TITLE
Jenkins runs sesdev with "--image-path null"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#152]
The new automated deployment test has a glitch:

```
+ sesdev create octopus --non-interactive --image-path null --qa-test --single-node mini
=== Creating deployment with the following configuration ===
1 Deployment VMs:
  -- admin:
     - OS:               leap-15.2
     - ses_version:      octopus
     - deployment_tool:  orchestrator
     - roles:            ['mds', 'igw', 'storage', 'prometheus', 'grafana', 'ganesha', 'mon', 'rgw', 'mgr', 'admin']
     - fqdn:             admin.mini.com
     - public_address:   10.20.47.200
     - cpus:             2
     - ram:              4G
     - storage_disks:    4
                         (device names will be assigned by vagrant-libvirt)
     - repo_priority:    True
     - qa_test:          True
     - image_path:       null
```

**Comment by toabctl** [comment]
I'll take a look into that.

**Comment by smithfarm** [comment]
@toabctl Actually, the `--image-path` is unnecessary, since sesdev already defaults to the path Jenkins is supposed to be specifying. See #153.

**Comment by toabctl** [comment]
@smithfarm if we want to use the job for other branches, we need to have this configurable I think. Or just rely on the defaults from sesdev?

**Comment by smithfarm** [comment]
> if we want to use the job for other branches, we need to have this configurable I think

Which branches are you referring to? 

> Or just rely on the defaults from sesdev?

With the Jenkins job as it is now, it should use the default image path. Maybe we could drop this parameter now, and make it configurable later when there is a use case for it?

It **does** make sense for it to specify `--ceph-salt-repo https://github.com/ceph/ceph-salt --ceph-salt-branch master`, though.
