### ISSUE TITLE
bug: provision destination needs trailing slash if directories are copied

### ISSUE THREAD

**Issue by jschmid1** [SUSE/sesdev#155]
when invoking sesdev with:

`sesdev create ses7 --single-node --qa-test test_ses7 `

it will fail on the provisioning (file) phase with:

```
DEBUG ssh: Uploading: $sesdev_path_to_qa to /home/vagrant/sesdev-qa
DEBUG ssh: Re-using SSH connection.
ERROR warden: Error occurred: scp: error: unexpected filename: .
```

This is probably due to how the `destination` key in the Vagrantfile is implemented.

`node.vm.provision "file", source: "{{ sesdev_path_to_qa }}", destination: "/home/vagrant/sesdev-qa"` <- no trailing slash will look for a `.` in `sesdev_path_to_qa`

Adding the trailing slash actually fixes this issue by copying the entire directory `sesdev_path_to_qa` under `/home/vagrant/sesdev-qa/`

-> `/home/vagrant/sesdev-qa/qa/$content_of_qa_dir`

**Comment by smithfarm** [comment]
@jschmid1 Are you running sesdev from source or from RPM?

**Comment by smithfarm** [comment]
Also, which version of sesdev - include output of `sesdev --version`

**Comment by smithfarm** [comment]
Here's what I see on the latest version of sesdev (installed from source):

```
==> admin: Running provisioner: file...
    admin: /home/smithfarm/sesdev/sesdev/../qa/ => /home/vagrant/sesdev-qa
==> admin: Running provisioner: shell...
    admin: Running: /tmp/vagrant-shell20200311-17616-to8qgo.sh
    admin: ++ ls -lR /home/vagrant
    admin: /home/vagrant:
    admin: total 8
    admin: drwxr-xr-x 2 vagrant vagrant 4096 Oct  9 04:36 bin
    admin: drwxr-xr-x 3 vagrant vagrant 4096 Mar 11 15:19 sesdev-qa
    admin:
    admin: /home/vagrant/bin:
    admin: total 0
    admin:
    admin: /home/vagrant/sesdev-qa:
    admin: total 12
    admin: drwxr-xr-x 2 vagrant vagrant 4096 Mar 11 15:19 common
    admin: -rwxr-xr-x 1 vagrant vagrant 3743 Mar 11 15:19 health-ok.sh
    admin: -rw-r--r-- 1 vagrant vagrant 1415 Mar 11 15:19 README.rst
    admin:
    admin: /home/vagrant/sesdev-qa/common:
    admin: total 20
    admin: -rw-r--r-- 1 vagrant vagrant 7091 Mar 11 15:19 common.sh
    admin: -rw-r--r-- 1 vagrant vagrant 1368 Mar 11 15:19 helper.sh
    admin: -rw-r--r-- 1 vagrant vagrant  628 Mar 11 15:19 json.sh
    admin: -rw-r--r-- 1 vagrant vagrant  516 Mar 11 15:19 zypper.sh
```

**Comment by smithfarm** [comment]
For completeness, please let us know which OS and which version of vagrant and vagrant-libvirt.

**Comment by jschmid1** [comment]
```
➜  ~ cat /etc/os-release          
NAME="openSUSE Leap"
VERSION="15.1"
➜  ~ vagrant --version 
Vagrant 2.2.0
➜  ~ vagrant plugin list
vagrant-libvirt (0.0.45, global)
```

Mh.. I do think this is related to my setup somehow..

**Comment by smithfarm** [comment]
Sounds like you don't have `Virtualization:vagrant` added. See the sesdev README.

On my Leap 15.1 machine I have:

```
$ vagrant --version
Vagrant 2.2.7
```

and

```
$ sesdev --version
sesdev 1.1.7
```

**Comment by jschmid1** [comment]
Confirmed that this is related to the vagrant version. Closing
