### ISSUE TITLE
`sesdev destroy` should tear down virtual networks

### ISSUE THREAD

**Issue by LenzGr** [SUSE/sesdev#17]
When running `sesdev destroy`, it correctly removes all associated VMs and their disk images. However, it fails to also tear down the virtual networks belonging to that deployment.

![Screenshot from 2019-11-21 10-33-30](https://user-images.githubusercontent.com/263427/69325607-4ef0cc00-0c42-11ea-94a6-7aad0f1f7497.png)

**Comment by jan--f** [comment]
Hmm iirc vagrant can't remove libvirt networks. So this would have to be done via libvirt directly. Also with #39 some care is needed.

In a way this missing vagrant feature (remove networks) was the original motivation for #39.

**Comment by jecluis** [comment]
yeah, and the problem with this, I find, is that `virsh` will require super cow permissions...

**Comment by smithfarm** [comment]
It's not fully automated, but #102 gave us `sesdev destroy --destroy-networks`.

From what I can see, `vagrant destroy --force` (which is what sesdev does) sometimes destroys/undefines the associated network and sometimes not. Not sure how it arrives at its decision.

The README now mentions this new option and there's a section in the "Common Pitfalls" chapter with a handy script for blowing away a bunch of networks at once.

If anyone has any ideas on how to fix this issue in a better way, please come forward with them by opening a new issue or, better yet, a PR.
