### ISSUE TITLE
Cluster comes up in "HEALTH_WARN: clock skew detected"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#185]
I've been deploying multi-node octopus 15.2.0 clusters on SLE-15-SP2 and consistently they are coming up with:

```
HEALTH_WARN
clock skew detected on mon.node
```

The reason for this is ceph-salt starts chronyd on the cluster nodes, but does not wait for them to sync. Typically there is a multi-second (even tens of seconds) skew between the `time_server` cluster node and the external time servers when chronyd first starts. Now, of course, chronyd will eventually sync, but the larger the skew, the longer it takes.

Since this initial health warning has a negative psychological impact on the user (who may not even know what a "clock skew" is), it would be nicer if we avoided the warning by syncing the clocks **before** deploying any additional MONs post-bootstrap. 

NOTE: The first MON is deployed by `cephadm bootstrap`, but this one by itself will never get into a clock skew state. Clock skew can only happen with multiple MONs.

**Comment by sebastian-philipp** [comment]
actually, why not fix this in ceph-salt itself? also production clusters should not start with a clock-skew

**Comment by smithfarm** [comment]
> actually, why not fix this in ceph-salt itself? also production clusters should not start with a clock-skew

My understanding is that, very soon, `ceph-salt deploy` will stop after `cephadm bootstrap`, i.e. in a state when only one MON is deployed. A single MON will never suffer from a clock skew.
