### ISSUE TITLE
Stop multiple clusters using a single command

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/sesdev#193]
It would be useful if we can stop multiple clusters by running, for instance: 

```
# sesdev stop *
```

The same applies to `destroy` and other commands.

**Comment by smithfarm** [comment]
Globbing is easy to implement in Python:

```
import fnmatch

matching = fnmatch.filter(arbitrary_list, glob_pattern)
```

Demo:

```
>>> import fnmatch
>>> abc = [ 'node1', 'node2', 'foo' ]
>>> fnmatch.filter(abc, 'n*')
['node1', 'node2']
>>> fnmatch.filter(abc, '*[12]*')
['node1', 'node2']
>>> fnmatch.filter(abc, '*[3]*')
[]
```

**Comment by smithfarm** [comment]
Some more thoughts:

1. This can be implemented entirely in `sesdev/__init__.py`. First, using a regex, determine whether the provided argument `deployment_id` is a glob (look for characters `[]{}*?`). If it's a glob, use `seslib.Deployment.list` to get a list of all deployments and apply the filter to the deployment IDs in the list. Then loop over the matches.
2. Globbing should only work with `--non-interactive/--force`. If a glob is given without said option, then raise an exception.
