### ISSUE TITLE
allow user-defined nfs mounts provided via the cli

### ISSUE THREAD

**Issue by jschmid1** [SUSE/sesdev#237]
Vagrant allows nfs shares to be mounted inside a VM (https://www.vagrantup.com/docs/synced-folders/nfs.html).

sesdev doesn't use this feature currently.
https://github.com/SUSE/sesdev/blob/78f238a80861b2e76cb7f82287a6c80281ae242e/seslib/templates/Vagrantfile.j2#L28

Having a option to pass an arbitrary directory that will get mounted on the master is going to be helpful for cephadm/ceph-volume devlopment (or testing in general).
This allows you to change files on your local file system with your favorite editor and have them in sync on the VM you're working on. It also avoids copying directories back and forth.

Maybe something like this:

`sesdev .... --sync-folder|--nfs-mount <path_to_dir=path_to_mount>`
 
the separator needs some discussion. '=', '-', ':'. Podman uses a colon for this, so maybe we should stay with this convention

**Comment by smithfarm** [comment]
This would be a fine feature to have, I think.

Given that the vagrant option is `synced_folder`, would it make sense to call the option `--synced-folder` ?

**Comment by smithfarm** [comment]
And, I might add, adhering to Podman's `:` convention sounds reasonable.

**Comment by smithfarm** [comment]
Question: will multiple instances of the option be supported (for syncing multiple folders), or just one?

**Comment by jschmid1** [comment]
> Given that the vagrant option is `synced_folder`, would it make sense to call the sesdev option `--synced-folder` ?

Let's go with `synced-folder`


> Question: will multiple instances of the option be supported (for syncing multiple folders), or just one?

I'd say so.  Either

`--synced-folder src1:dst1 src2:dst2`

or

`--synced-folder src1:dst1 --synced-folder src2:dst2`

Depending on what the argparser will accept more easily I think.



> And, I might add, adhering to the Docker/Podman (`:`) convention sounds reasonable.

`:` it is then

**Comment by smithfarm** [comment]
> `--synced-folder src1:dst1 src2:dst2`

This would have to be `--synced-folder "src1:dst1 src2:dst2"` if you wanted to go this route - otherwise Click would interpret the second pair as an argument (positional).

> `--synced-folder src1:dst1 --synced-folder src2:dst2`

This one gets my vote.
