### ISSUE TITLE
feature request: user control over time synchronization

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#240]
In order to provide a smooth user experience, sesdev tries to configure time synchronization:

* install ntp/chrony
* configure master to get time from a remote timeserver
* configure minions to get time from master

Different versions of the product are in different states when it comes to configuring time synchronization. For example, DeepSea in SES5 seems to require that the user set up ntp and ensure clocks are synced before running Stages. For other versions of the product, it might be sufficient to configure chrony on the master and the product's deployment tooling will automatically configure the minions to get their time from the master.

In order to facilitate "time synchronization setup story" testing of different versions of our product, I propose to implement the following options to `sesdev create`:

* `--time-sync-setup` - a string option with values `{full, master, none}` (default: `full`)
* `--skew-clocks` - a bool option

`--time-sync-setup=full` would set up clock synchronization on all nodes and ensure clocks are in sync before starting the deployment.

`--time-sync-setup=master` would only set up time sync on the master node: all other nodes would be left untouched.

`--time-sync-setup=none` would do no time sync setup at all.

`--skew-clocks` would set the clocks to random values, ensuring that they are seriously out of sync, before starting the deployment.

**Comment by asettle** [comment]
SES 5 EOL
