### ISSUE TITLE
Extend --encrypted-osds to SES5

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#241]
The initial implementation of `--encrypted-osds` supports `nautilus` and `ses6` deployments only. This ticket is for expanding the coverage to `ses5`.

In `ses5`, we must issue the following commands between Stages 1 and 2:

    {% set policy_cfg = "/srv/pillar/ceph/proposals/policy.cfg" %}
    salt-run proposal.populate encryption=dmcrypt
    sed -i -e 's/^profile-default/profile-dmcrypt/' {{ policy_cfg }}
    cat {{ policy_cfg }}

From my reading, this **might** be sufficient. At least it's a start.

**Comment by asettle** [comment]
SES 5 EOL
