### ISSUE TITLE
CephFS smoke test

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#257]
In addition to counting the running MDSs, we could have a QA test that mounts CephFS using the kernel client, creates a file, deletes a file, and unmounts. Call it a "CephFS smoke test".

The test should only be triggered if there is a "client" role in the cluster.

First, the test should create a client keyring on one of the cluster (admin) nodes:

```
# ceph auth get-or-create client.cephfs mon 'allow r' mds 'allow r'
```

Then it should move or copy this "client.cephfs" keyring to the client node.

Then the test could proceed from here: https://docs.ceph.com/docs/mimic/start/quick-cephfs/#create-a-secret-file - except it would use the "client.cephfs" keyring/secret instead of the admin keyring.

**Comment by asettle** [comment]
Out of scope
