### ISSUE TITLE
dashboard tunnel fails

### ISSUE THREAD

**Issue by jschmid1** [SUSE/sesdev#269]
with:

`sesdev create ses7 --stop-before-ceph-salt-config`

```
➜  ~ sesdev tunnel ses7 dashboard
Opening tunnel to service 'dashboard' on node 'master'...
Node '' does not exist in this deployment
➜  ~ sesdev --version            
sesdev 1.1.10
```

**Comment by jschmid1** [comment]
this https://github.com/SUSE/sesdev/blob/c2b5a851f4007d61d92d7e470ff8e74122dc4d0f/seslib/__init__.py#L1725 
returns `''`, hence isn't caught by the except block.

**Comment by jschmid1** [comment]
When nodes/roles are assigned:

```
master:~ # ceph-salt config ceph_cluster/roles  ls
o- roles ...................................................................................................... [...]
  o- admin ............................................................................................. [Minions: 1]
  | o- master.ses7.com ..................................................................... [Other roles: bootstrap]
  o- bootstrap .................................................................................... [master.ses7.com]
```

I see that the `master` node does not have the mentioned roles assigned.

```
(Pdb) _node.name
'master'
(Pdb) _node.roles
['master', 'client', 'prometheus', 'grafana']
```

while `node1`, which doesn't have the roles assigned (in `config`) shows _does_ report it in the `Node` object.

```
(Pdb) _node.name
'node1'
(Pdb) _node.roles
['bootstrap', 'storage', 'mon', 'mgr', 'rgw', 'igw']
```

This leads to wrong targeting in the next block.

https://github.com/SUSE/sesdev/blob/c2b5a851f4007d61d92d7e470ff8e74122dc4d0f/seslib/__init__.py#L1720-L1722

and to a consecutive failure since the `ceph` binary is not installed on this node yet.

**Comment by smithfarm** [comment]
This is an interesting bug report. Thanks, @jschmid1, for opening it.

I understand *what* is happening, but I'm not sure how to fix it. Here is the "what":

When you don't specify any roles, `sesdev` gives you the default roles, which put `bootstrap` on node1.

You, however, manually told `ceph-salt` that "master" is the bootstrap node.

Another problem is that `sesdev tunnel ses7 dashboard` is not savvy. If you don't provide the name of the node, you get `master` by default.

You can work around this issue by:

1. knowing which node "cephadm bootstrap" was run on
2. providing that node on the `sesdev tunnel dashboard NODE` command line

**Comment by smithfarm** [comment]
Another idea would be to create the cluster like this:

```
sesdev create ses6 --roles="[master, bootstrap], [], [], []"
```
