### ISSUE TITLE
Nomenclature: rename "version" to "product" (or "release", or "flavor"?)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#272]
sesdev is a tool for deploying different Ceph in different environments. For example, when deploying Ceph in a SLE-15-SP1 environment, the expectation is that the latest SES6 code will be used.

Right now, sesdev uses the term "version" to mean the version of Ceph being deployed. It has the following possible values:

* ses5
* nautilus
* ses6
* octopus
* ses7
* pacific

However, the term "version" is unsatisfactory. Typically it means something like "14.2.9" and not "nautilus". The former is a "version", while the latter is a "release". On the other hand, SES6 is a "product".

This ticket is about renaming "version" to either "product" or "release" in sesdev.

Thoughts, anyone?

**Comment by toabctl** [comment]
Maybe flavor? Naming is hard :)
