### ISSUE TITLE
CaaSP clusters are not actually provisioned

### ISSUE THREAD

**Issue by colder-is-better** [SUSE/sesdev#299]
Currently, whenever we use `caasp4` as a target for the `create` command, we indeed end up with a set of SLE15SP1 nodes but with no _actual_ CaaSP 4 cluster. The nodes are prepared and ready for CaaSP 4 (i.e., the product, the patterns, and all required repositories/modules are there), but the CaaSP 4 cluster itself is not provisioned. Manual provisioning of CaaSP 4 is possible and works fine, but it would be nicer to issue a command like

```
sesdev create caasp4 --domain local.is \
	--num-disks 2 --disk-size 64 --ram 6 --cpus 4 \
	--roles="[master], [worker, storage], [worker, storage], [worker, storage]" \
	k8sbaby --non-interactive
```

and after a while have a fully working CaaSP 4 cluster. Additionally, including `--deploy-ses` on a command like the above would automatically install Rook over CaaSP 4. (Command `--deploy-ses` is already there, but for now it looks like it has no effect.)

**Comment by toabctl** [comment]
cc @capri1989 iirc you did some implementation during hackweek, right?

**Comment by capri1989** [comment]
I did the implementation during hackweek, yeah and I would need to look at it again. Will put on my backlog but can't promise when this will be done.

**Comment by capri1989** [comment]
https://github.com/SUSE/sesdev/pull/302

**Comment by smithfarm** [comment]
@colder-is-better Can this be closed now?

**Comment by colder-is-better** [comment]
It sure can -- thank you!

---
I survive (mostly) by tapping keys
Always remember: Colder Is Better (TM)
