### ISSUE TITLE
Expand CI to include CaaSP deployments

### ISSUE THREAD

**Issue by colder-is-better** [SUSE/sesdev#305]
Currently our CI automatically tests deployments of SES 7. Since we re-introduced support for CaaSP in `sesdev`, it would be nice (and useful) if our CI tested deployments of CaaSP also.

**Comment by smithfarm** [comment]
I see `sesdev` primarily as a tool for reproducing environments, not necessarily as a CI platform. Since we already have a caasp teuthology task [1], does that address your concern?

[1] https://github.com/SUSE/ceph/pull/370

**Comment by toabctl** [comment]
The task would be there to make sure, that `sesdev` **can** deploy a caasp/rook stack. Not to test caasp/rook itself.
I think the usecase is, that people (devs, doc writers, ...) want to have a simple way to setup caasp with rook, so `sesdev` might be the way to go. But we need to make sure that this does work.

**Comment by smithfarm** [comment]
Right now I have `contrib/standalone.sh` which I use to test PRs for regressions. It does run `sesdev create caasp4`, but I'll be the first to admit this is not sufficient to detect the recent regression.

"To make sure, that `sesdev` **can** deploy a caasp/rook stack. Not to test caasp/rook itself."

Can you provide more detail on what this means to you?

**Comment by toabctl** [comment]
> Right now I have `contrib/standalone.sh` which I use to test PRs for regressions. 

Are you running that manually for every PR?

> It does run `sesdev create caasp4`, but I'll be the first to admit this is not sufficient to detect the recent regression.
> 
> "To make sure, that `sesdev` **can** deploy a caasp/rook stack. Not to test caasp/rook itself."
> 
> Can you provide more detail on what this means to you?

Just similar to what we have in the `Jenkinsfile.integration` . So really just the basics like calling `sesdev create caasp ....`

**Comment by smithfarm** [comment]
> Are you running that manually for every PR?

Since it takes hours and hours to run, I gang the PRs together into an integration branch and then run it on that. I don't think running it on every PR (to say nothing of running it on every push to every PR) is feasible.

> So really just the basics like calling `sesdev create caasp ....`

**Comment by toabctl** [comment]
> I'm especially curious about the part beyond the "...." ;-)

I don't know that yet. I'm just assuming that there is something similar to:

`sesdev create octopus --non-interactive --ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master --single-node mini`

for caasp. Isn't there?

**Comment by smithfarm** [comment]
> > I'm especially curious about the part beyond the "...." ;-)
> 
> I don't know that yet. I'm just assuming that there is something similar to:
> 
> `sesdev create octopus --non-interactive --ceph-salt-repo https://github.com/ceph/ceph-salt.git --ceph-salt-branch master --single-node mini`
> 
> for caasp. Isn't there?

You mean whether there is an option to `sesdev create caasp4` to deploy Rook from source, or to deploy CaaSP itself from source? Or both?

**Comment by colder-is-better** [comment]
It's possible to have a single-node k8s cluster (think Minikube: https://kubernetes.io/docs/tasks/tools/install-minikube), but I'm not sure `skuba` can deploy a single-node CaaSP cluster. According to https://documentation.suse.com/suse-caasp/4.2/html/caasp-deployment/deployment-system-requirements.html#_nodes, you need at least two nodes (a master and a worker).

**Comment by toabctl** [comment]
> You mean whether there is an option to `sesdev create caasp4` to deploy Rook from source, or to deploy CaaSP itself from source? Or both?

Well - given that this is `sesdev` I'm interested in rook on top of caasp.

> Also, I'm not sure what a single-node CaaSP cluster looks like... is there such a thing even?

Then let's use 3 nodes and call it `mini`. That's also imo details.
What I want is a single command to setup a CaaSP 4 (or 5 when availble) cluster and install on top of that our rook package (or maybe later rook from source).
So devs, doc writers, ... have some simple step to get something to play with.

**Comment by smithfarm** [comment]
Sounds like rook is delivered as a container, not as an RPM...

**Comment by colder-is-better** [comment]
We actually have an RPM for Rook:

```
master:~ # zypper if rook-k8s-yaml
Loading repository data...
Reading installed packages...

Information for package rook-k8s-yaml:
--------------------------------------
Repository     : storage-update                                             
Name           : rook-k8s-yaml                                              
Version        : 1.1.1+git0.g9a2641a6-1.14.1                                
Arch           : noarch                                                     
Vendor         : SUSE LLC <https://www.suse.com/>                           
Support Level  : Level 3                                                    
Installed Size : 180.9 KiB                                                  
Installed      : No                                                         
Status         : not installed                                              
Source package : rook-1.1.1+git0.g9a2641a6-1.14.1.src                       
Summary        : Kubernetes YAML file manifests for deploying a Ceph cluster
Description    :                                                            
    This package contains the yaml files required to deploy and run the
    Rook-Ceph operator and Ceph clusters in a Kubernetes cluster.
```

If you take a look at the contents of said package, you will see lots of YaML files. We use `kubectl` on specific YaML files to actually deploy Rook. Since Rook supports many storage providers (Ceph, CockroachDB, NFS, etc), a typical deployment for Ceph would go like this:
 
```
master:~ # cd /usr/share/k8s-yaml/rook/ceph
master:/usr/share/k8s-yaml/rook/ceph # kubectl create -f common.yaml
master:/usr/share/k8s-yaml/rook/ceph # kubectl create -f operator.yaml
master:/usr/share/k8s-yaml/rook/ceph # kubectl create -f cluster.yaml
master:/usr/share/k8s-yaml/rook/ceph # kubectl create -f toolbox.yaml
```

**Comment by smithfarm** [comment]
`contrib/standalone.sh` includes `sesdev create caasp4`, so I'd say we have this covered.
