### ISSUE TITLE
Modify default CaaSP deployment

### ISSUE THREAD

**Issue by colder-is-better** [SUSE/sesdev#308]
When trying out the default CaaSP deployment, e.g., by typing...

```
sesdev create caasp4 --non-interactive dascaasp
```

...we end up with four VMs: `master`, `worker1`, `loadbl1`, and `storage1`:

```
(venv) sub0@ísafjörður:~/colder/sesdev> sesdev list
Found 1 deployment:

+----------+---------+---------+------------------------------------+
| ID       | Version | Status  | Nodes                              |
+----------+---------+---------+------------------------------------+
| dascaasp | caasp4  | running | master, worker1, loadbl1, storage1 |
+----------+---------+---------+------------------------------------+
```

Of those VMs, `master`, `worker1`, and `loadbl1` comprise a (minimal) CaaSP cluster:

```
master:~ # kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
master    Ready    master   17m   v1.17.4
worker1   Ready    <none>   16m   v1.17.4
```

(Please note that `loadbl1` is not in the output of `kubectl get nodes`, but that does not mean it is not used -- see, for example, `/root/.kube/config`.)

The remaining VM, `storage1`, is up and running, but it is not used. Even when we deploy Rook over CaaSP, the OSD pods use any extra block devices in the worker nodes (by default, we have two extra block devices per worker). For instance, let us try the default CaaSP deployment and __also__ install Rook:

```
sesdev create caasp4 --deploy-ses --non-interactive muhrook
```

When deployment is complete, we take a look at the pods of the `rook-ceph` namespace:

```
master:~ # kubectl get pods -n rook-ceph
NAME                                           READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-dgrhq                         3/3     Running     0          62m
csi-cephfsplugin-provisioner-f5fd74bfc-kvlsc   4/4     Running     0          62m
csi-cephfsplugin-provisioner-f5fd74bfc-w6gxq   4/4     Running     0          62m
csi-rbdplugin-provisioner-889bb9fb9-rtpc2      5/5     Running     0          62m
csi-rbdplugin-provisioner-889bb9fb9-tkdxc      5/5     Running     0          62m
csi-rbdplugin-rzpj4                            3/3     Running     0          62m
rook-ceph-mgr-a-84cffd79c6-8sdxl               1/1     Running     0          57m
rook-ceph-mon-a-988886487-57j7v                1/1     Running     0          59m
rook-ceph-mon-b-6687bfd696-kz8v2               1/1     Running     0          58m
rook-ceph-mon-c-5549dbd6d7-c9bmk               1/1     Running     0          58m
rook-ceph-operator-5468fd7fbd-6wcx8            1/1     Running     0          63m
rook-ceph-osd-0-5646cf494-jsmp6                1/1     Running     0          56m
rook-ceph-osd-1-8fd566f47-8rd5j                1/1     Running     0          56m
rook-ceph-osd-prepare-worker1-885jz            0/1     Completed   0          57m
rook-ceph-tools-7994589fb5-mzsm9               1/1     Running     0          62m
rook-discover-xn2hc 
```

We have two OSD pods (`rook-ceph-osd-0-5646cf494-jsmp6`, `rook-ceph-osd-1-8fd566f47-8rd5j`), corresponding to the `vdb` and `vdc` block devices of `worker1`. Again, VM `storage1` is there...

```
(venv) sub0@ísafjörður:~/colder/sesdev> sesdev list
Found 1 deployment:

+---------+---------+---------+------------------------------------+
| ID      | Version | Status  | Nodes                              |
+---------+---------+---------+------------------------------------+
| muhrook | caasp4  | running | master, worker1, loadbl1, storage1 |
+---------+---------+---------+------------------------------------+
```

...but not used.

Since we are mostly interested in Rook, and therefore we need CaaSP, maybe we should change the default CaaSP deployment for `sesdev`. Specifically, we could slightly modify it to involve one master node, two worker nodes, and a load balancer node. In other words, we could skip the node with role `storage`, have a slightly more interesting CaaSP cluster __and__ a slightly more interesting Rook deployment as a bonus.

**Comment by smithfarm** [comment]
> In other words, we could skip the node with role storage, have a slightly more interesting CaaSP cluster and a slightly more interesting Rook deployment as a bonus.

My assumption would be that nodes with the `storage` role should get the Ceph cluster. But it sounds like, due to some bug, `sesdev create caasp4` is deploying it on the nodes with role `worker`.

If we drop `storage` from the default caasp4 deployment (in favor of `worker`), then we might as well just rip out the `storage` role completely, right? Alternatively, the `storage` role could be fixed.

**Comment by colder-is-better** [comment]
Actually, I modified the default deployment like this...

```
diff --git a/seslib/__init__.py b/seslib/__init__.py
index 287ecc9..87f41dc 100644
--- a/seslib/__init__.py
+++ b/seslib/__init__.py
@@ -223,7 +223,7 @@ VERSION_DEFAULT_ROLES = {
     'nautilus': NAUTILUS_DEFAULT_ROLES,
     'octopus': OCTOPUS_DEFAULT_ROLES,
     'pacific': OCTOPUS_DEFAULT_ROLES,
-    'caasp4': [["master"], ["worker"], ["loadbalancer"], ["storage"]],
+    'caasp4': [["master"], ["worker"], ["worker"], ["loadbalancer"]],
     'makecheck': [["makecheck"]],
 }
```

...and then I went ahead and deployed:

```
sesdev create caasp4 --deploy-ses -n muhrook
```

After `sesdev` was done, all was well (including Rook, of course):

```
master:~ # kubectl get pods -n rook-ceph
NAME                                           READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-lnxqj                         3/3     Running     0          8m52s
csi-cephfsplugin-provisioner-f5fd74bfc-9qtr4   4/4     Running     0          8m54s
csi-cephfsplugin-provisioner-f5fd74bfc-g484j   4/4     Running     0          8m54s
csi-cephfsplugin-vpmsv                         3/3     Running     0          8m52s
csi-rbdplugin-6f82b                            3/3     Running     0          8m53s
csi-rbdplugin-provisioner-889bb9fb9-bvn5l      5/5     Running     0          8m54s
csi-rbdplugin-provisioner-889bb9fb9-txn55      5/5     Running     0          8m54s
csi-rbdplugin-v4j8b                            3/3     Running     0          8m53s
rook-ceph-mgr-a-65dfbb954b-xnh58               1/1     Running     0          2m32s
rook-ceph-mon-a-56c4f7f979-jj7p5               1/1     Running     0          4m20s
rook-ceph-mon-b-66c7c7dccf-9wcd8               1/1     Running     0          3m52s
rook-ceph-mon-c-b94b89c6f-gmrbr                1/1     Running     0          3m1s
rook-ceph-operator-5468fd7fbd-lhc52            1/1     Running     0          10m
rook-ceph-osd-0-7cb475b786-rxjlz               1/1     Running     0          43s
rook-ceph-osd-1-84df85c6f5-gzl49               1/1     Running     0          32s
rook-ceph-osd-2-c68d57856-89wvj                1/1     Running     0          43s
rook-ceph-osd-3-797c4bd98f-thjgq               1/1     Running     0          32s
rook-ceph-osd-prepare-worker1-vchfs            0/1     Completed   0          114s
rook-ceph-osd-prepare-worker2-j2sqn            0/1     Completed   0          114s
rook-ceph-tools-7994589fb5-pl5wk               1/1     Running     0          8m54s
rook-discover-r7x4l                            1/1     Running     0          8m53s
rook-discover-vglkj                            1/1     Running     0          8m53s
```

(Four OSD pods, as expected.) So it looks like we can safely rip the `storage` role. I will create a PR.

**Comment by colder-is-better** [comment]
OK, after reading through the code a bit more carefully, I now see that the `storage` role can actually make sense when deploying a CaaSP cluster. So when we do include that role, we get a node acting as an NFS server. That server provides persistent storage to containers that may request it, via an `nfs-client` pod which is instantiated in the cluster with `helm`.

The fact of the matter remains, though: We are mostly interested in Rook/Ceph, so the default CaaSP deployment does not need/should not involve persistent stores via nodes acting as NFS servers. So, to sum things up:

* I propose a default CaaSP deployment with one master, two workers, and one load balancer. Rook will be using the OSDs of the worker nodes (two OSDs per worker by default).
* When, for whatever reason, the user wants a CaaSP cluster with an NFS store and possibly without Rook/Ceph, they will still have the option to include the `storage` role in the `--roles` parameter. Examples: `sesdev create caasp4 --roles="[master], [worker], [worker], [loadbalancer], [storage]" -n dascaasp` (we don't get Rook but we get an NFS store instead), or `sesdev create caasp4 --deploy-ses --roles="[master], [worker], [worker], [loadbalancer], [storage]" -n dascaasp` (we get Rook and also an NFS store).

**Comment by smithfarm** [comment]
@colder-is-better @capri1989 @toabctl I was just now re-reading this issue and PR #310 and one thought occurred to me:

First: with #310 we are by default no longer deploying an NFS server to provide storage to the CaaSP4 cluster.

However, second: by default, no Rook/Ceph cluster is deployed when we run `sesdev create caasp4`.

Does this mean that, with #310 as it currently stands, sesdev will by default deploy CaaSP4 clusters without any storage whatsoever (unless additional options are provided on the `sesdev create caasp4` command line)?

If the answer to that question is "yes", I think it would make sense, in #310, to make `--deploy-ses` be the default. I.e., a user would need to explicitly provide an option (`--no-deploy-ses`) on the command line to get a CaaSP4 deployment **without** Rook/Ceph.

Specifically, I'm proposing to integrate this additional change into #310:

sesdev/__init__.py:

```
- @click.option("--deploy-ses", is_flag=True, default=False,
+ @click.option("--deploy-ses/--no-deploy-ses", is_flag=True, default=True,
                help="Deploy SES using rook in CaasP")
```

```
-     if deploy_ses:
-         settings_dict['caasp_deploy_ses'] = True
+     if not deploy_ses:
+         settings_dict['caasp_deploy_ses'] = False
```

seslib/__init__.py:

```
      'caasp_deploy_ses': {
          'type': bool,
          'help': 'Deploy SES using rook in CaasP',
-         'default': False,
+         'default': True,
      },  
```
What do you think?

**Comment by colder-is-better** [comment]
Well, whenever we deploy CaaSP or a k8s cluster in general for testing/learning/experimentation, we do not necessarily need an "externally provided" persistent sore, like an NFS server. Of course, when we need a persistent store _after the fact_ we can surely configure one. But in any case, this is `sesdev` so --at least in my mind-- at some point we added support for CaaSP __exactly because__ of Rook. So, IMO, the defaults regarding the deployment of CaaSP and/or Rook are fine as they are: We either want a SUSE-flavored k8s cluster to quickly check something/play arround, so `sesdev create caasp4 dascaasp` does the trick, or we want a full-featured Rook/Ceph deployment, so `sesdev create caasp4 --deploy-ses dasrook` does the trick. In not so many words, I think we should not complicate things any further.

PS. The above doesn't mean there's no room for improvement regarding `sesdev` and CaaSP. We could, for example, make the use of a load balancer optional when we have only one master, or re-introduce proper multi-master support. (I haven't checked recently, but if I'm not mistaken this is not properly supported ATM.)
