### ISSUE TITLE
Use "ceph nfs create" once it becomes available

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#338]
There are plans afoot to implement a "ceph nfs create" command.

sesdev should use that to deploy NFS Ganesha, once it becomes available.

**Comment by sebastian-philipp** [comment]
https://docs.ceph.com/docs/master/cephfs/fs-nfs-exports/

**Comment by smithfarm** [comment]
waiting for this to be merged into octopus: https://github.com/ceph/ceph/pull/35499
