### ISSUE TITLE
deploying sesdev on OpenStack - orchestrate the process

### ISSUE THREAD

**Issue by asettle** [SUSE/sesdev#339]
To deploy sesdev on OpenStack, you currently have to run through a series of tasks within the cloud and then run the instructions to deploy sesdev. It's not hard, but it's time consuming for someone who wants to quickly spin up an instance to check something - which is exactly what OpenStack and sesdev is designed for.

This could be made easier by combining these actions with an orchestrator tool - ansible, salt, etc.

**Comment by smithfarm** [comment]
Sounds like something that would go in `contrib/`
