### ISSUE TITLE
Don't show the hint to access the Dashboard when it has not been deployed

### ISSUE THREAD

**Issue by LenzGr** [SUSE/sesdev#349]
This is more a cosmetic thing or an irritation if you will, but when I deploy an ses7 or octopus cluster with the option `--stop-before-ceph-salt-config`, the dashboard won't be up and running when `sesdev` finishes:
```
=== Deployment Finished ===

You can login into the cluster with:

  $ sesdev ssh ses7

Or, access the Ceph Dashboard with:

  $ sesdev tunnel ses7 dashboard

$ sesdev tunnel ses7 dashboard
Opening tunnel to service 'dashboard' in deployment 'ses7'...
Service 'dashboard' was not found in this deployment
```
Maybe that message should be suppressed when this option (or any other of the `--stop-before-*` options) is used?

**Comment by smithfarm** [comment]
Yes! Related issue: #312
