### ISSUE TITLE
Provide a way to connect two sesdev clusters

### ISSUE THREAD

**Issue by trociny** [SUSE/sesdev#396]
If I deploy two sesdev clusters the network connection between them is forbidden on iptables level. Sometimes we need to connect the clusters though (I needed it for testing RBD mirroring. And I can imagine it could be useful for testing RGW multisite or CephFS snapshots sync).

I found a way to just manually tweak the iptables rules after the clusters are deployed. Though I believe there is a nicer way or it could be implemented (documented).

**Comment by smithfarm** [comment]
https://github.com/ldx/python-iptables
