### ISSUE TITLE
sesdev cluster suspends after indetermined timeframe - unable to restart

### ISSUE THREAD

**Issue by asettle** [SUSE/sesdev#426]
Context: I have a successfully deployed ses7 cluster running in ECP. I have been able to have the cluster up and running, access the dashboard, etc. 

Issue: In an undetermined amount of time my cluster appears to disconnect completely and drop my SSH connection. I will log back in, and attempted to tunnel back into the dashboard. I receive the following error:

![Screenshot from 2020-08-12 13-48-53](https://user-images.githubusercontent.com/1987994/90016962-b6ecb400-dca2-11ea-9835-aa08a4ba0efc.png)

Once I've SSH'd back into my cluster, I find my deployment has automatically suspended itself:

![Screenshot from 2020-08-12 13-47-58](https://user-images.githubusercontent.com/1987994/90016872-94f33180-dca2-11ea-82c2-e99b2197abbf.png)

I've attempted a few variations here to determine what the problem is, but I'm limited. I try to start my cluster using `sesdev start ses7`. The message is successful:

```sesdev-dashboard:~ # sesdev start ses7
Starting 1 cluster
=== Running shell command ===
vagrant up
Bringing machine 'master' up with 'libvirt' provider...
Bringing machine 'node1' up with 'libvirt' provider...
Bringing machine 'node2' up with 'libvirt' provider...
Bringing machine 'node3' up with 'libvirt' provider...
==> node3: Resuming domain...
==> node2: Resuming domain...
==> node1: Resuming domain...
==> master: Resuming domain...
Deployment ses7 started!
```
 However, after running `sesdev list` again, I find my cluster is still in the `suspended` state. I try again with stopping the cluster using `sesdev stop ses7`, but it remains suspended. 

According to `qa-test` my instance is stopped. 

![Screenshot from 2020-08-12 13-53-23](https://user-images.githubusercontent.com/1987994/90017377-590c9c00-dca3-11ea-913f-e553cac275ce.png)

I attempt to start again, but `sesdev list` is still showing as `suspended`. 

I'm at a loss, nothing changed. I've only been clicking around the Dashboard getting screenshots. This happened last night as well, when I came in this morning I was successfully able to run `sesdev redeploy ses7` and we came back up again.

**Comment by asettle** [comment]
To clarify a few things:

1. My ECP VM that sesdev is running on is up and has had no downtime. 
![Screenshot from 2020-08-12 14-07-36](https://user-images.githubusercontent.com/1987994/90018760-557a1480-dca5-11ea-96b2-41776126be5f.png)

2. After restarting the ECP VM, `sesdev list` now returns that the deployment is in a `stopped` state. 
![Screenshot from 2020-08-12 14-10-27](https://user-images.githubusercontent.com/1987994/90019008-b99cd880-dca5-11ea-9aeb-e0b3516b0714.png)

3. I run `sesdev start ses7` and it gets to this point (see below) and hangs:
![Screenshot from 2020-08-12 14-15-23](https://user-images.githubusercontent.com/1987994/90019496-69724600-dca6-11ea-9526-2e9179045aae.png)

The restart never finishes, I get a `partially complete` state, and then an error if I try again. My only option is to run `sesdev redeploy ses7` and start again.

**Comment by asettle** [comment]
To which it only partially deployed. ARGH.

**Comment by asettle** [comment]
So, looking at the partial deploy - it complained (after initiating the redeploy) that it couldn't do anything with node2 and master, but continued with node1 and node 3, resulting in a partial deploy. Looking at the libvirt instances master and node2 were in a `paused` state. After destroying and undefining those instances - node 2 and master (using virsh), only then would the redeploy succeed.

Expected behaviour: redeploy can tell the state and completely performs a full redeploy. 

If this is not the case, then the documentation needs to be clearer about the steps to take before a redeploy (aka, everything needs to be destroyed, and then redeployed). In that case, this may work: https://github.com/SUSE/sesdev#when-sesdev-deployments-get-destroyed-virtual-networks-get-left-behind but it's also not clear that it's the same option because in theory (according to the `--help` you should be able to simply issue `sesdev redeploy` without crashing first.

In any case, this doesn't explain why my instance just suspends itself in the first place.

**Comment by smithfarm** [comment]
The reason why the deployment got suspended in the first place is unclear. Did you suspend the OpenStack VM/instance via the Horizon Dashboard? Or it might have happened due to some obscure and possibly buggy interaction between the nested libvirts (i.e. the one running on the OpenStack node and the one running in the OpenStack VM/instance).

I'm afraid no fix is forthcoming at the sesdev level and you'll have to work around this by changing your workflow. I typically do not leave sesdev clusters running unattended. I either `sesdev stop` or `sesdev destroy` them. I don't use `sesdev redeploy` at all. Maybe we should just drop `redeploy`?

Well, there is one thing we could do at the sesdev level, and that's to implement a `sesdev list --detail` which would show the status of each node in addition to the overall deployment status. That might shed more light on the problem.
