### ISSUE TITLE
NFS-Ganesha: man pages missing in container

### ISSUE THREAD

**Issue by supriti** [SUSE/sesdev#428]
I tried with octopus cluster. 'man' is not pre installed in container image and hence, nfs-ganesha does not install man pages. I am not sure about how container images are handled but we should add man to it.

**Comment by smithfarm** [comment]
This isn't related to sesdev, though, right?

**Comment by smithfarm** [comment]
Also, I filed a bugzilla for this a couple weeks back. This is a thorny
issue, indeed. It's not clear how to solve it, other than simply doing
without manpages. (Putting the manpages in the container seems like a
non-starter, since the container is supposed to be transparent to the user.)

**Comment by supriti** [comment]
> This isn't related to sesdev, though, right?

True. I will close this issue here and can have discussion on related jira issue.

**Comment by smithfarm** [comment]
I found the Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1174698
