### ISSUE TITLE
sesdev tries to install python2-pip on Python3 system

### ISSUE THREAD

**Issue by votdev** [SUSE/sesdev#430]
When running `sesdev replace-mgr-modules ses7-mini --pr <ID>` the package `python2-pip` is tried to be installed, but that fails because SES7 is Python3 only.

```
 ~/git/sesdev   master ✔  $ sesdev replace-mgr-modules ses7-mini --pr 36611
Fetching PR '36611' from 'ceph'...
Disabling modules...

Fetching...
Building...
Command '['ssh', 'root@192.168.121.98', '-i', '/home/vot/.sesdev/ses7-mini/keys/sesdev', '-o', 'IdentitiesOnly yes', '-o', 'StrictHostKeyChecking no', '-o', 'UserKnownHostsFile /dev/null', '-o', 'PasswordAuthentication no', "cd ~/ &&                 zypper -n in python2-pip python3-pip &&                 pip install nodeenv &&                 nodeenv env --node=10.18.1 --force &&                 . ~/env/bin/activate &&                 cd /root/remote/ceph/src/pybind/mgr/dashboard/frontend &&                 export DASHBOARD_FRONTEND_LANGS='en-US' &&                 export NG_CLI_ANALYTICS=false &&                 npm ci --unsafe-perm &&                 npm run build &&                 rm -rf node_modules"]' failed: ret=104 stderr:
b"Warning: Permanently added '192.168.121.98' (ECDSA) to the list of known hosts.\r\nKeine Anbieter von 'python2-pip' gefunden.\n"
```

**Comment by smithfarm** [comment]
This was introduced by https://github.com/SUSE/sesdev/pull/24 and I've commented there, but the simple fix would be to drop `python2-pip` from this line:

```
zypper -n in python2-pip python3-pip && \
```

I'll leave it to @tspmelo to fix, though, since it's his code.

**Comment by tspmelo** [comment]
We still need that for nautilus based clusters.
The solution should be to check what kind of cluster we have and install one or the other.

It seems this only fails when all other packages are already installed, otherwise zypper doesn't complain, and must have escaped my testing.

I will be on vacation next week. Will work on it after it.

**Comment by smithfarm** [comment]
> We still need that for nautilus based clusters.

@tspmelo Why do you think Python 2 is needed in Nautilus/SES6, though? While it is true that `zypper in python2-pip` will bring in Python 2 if it's available in the repos, it should not be needed to run Ceph, except on SES5.

In fact, sesdev explicitly removes Python 2 from the system if it's present from the default image:

https://github.com/SUSE/sesdev/blob/master/seslib/templates/zypper.j2#L18-L21

> The solution should be to check what kind of cluster we have and install one or the other.

If Python 2 is not needed, then the problem disappears, no?

**Comment by tspmelo** [comment]
Python is needed to install node-env and a specific version of node. 
And node is needed to compile the dashboard frontend.

**Comment by smithfarm** [comment]
> Python is needed to install node-env and a specific version of node.
> And node is needed to compile the dashboard frontend.

I'm guessing you're referring to the part of `make-dist` starting with these lines:

```
$CURR_DIR/src/tools/setup-virtualenv.sh $TEMP_DIR
$TEMP_DIR/bin/pip install nodeenv
$TEMP_DIR/bin/nodeenv -p --node=10.13.0
```

This, too, works in a Python 3 virtualenv. Do you know why a Python 2 virtualenv is getting created in your case?

**Comment by smithfarm** [comment]
Ah, you're referring to these lines in #24 

```
                pip install nodeenv && \
                nodeenv env --node={} --force && \
                . ~/env/bin/activate && \
```

This should work fine in a Python 3-only system (I just tried it).

**Comment by tspmelo** [comment]
> Ah, you're referring to these lines in #24

yes

> This should work fine in a Python 3-only system (I just tried it).

I just though it failed in a ses6 or nautilus cluster, might have been some problem with my env.
But if not, we can simply remove all python2 packages.
