### ISSUE TITLE
"ceph device ls" does not work

### ISSUE THREAD

**Issue by p-se** [SUSE/sesdev#48]
`ceph device ls` does not work. It returns no devices. This is probably due to the virtual machines having not sufficient device meta data (vendor, serial number, etc) for a device ID to be generated.

This is on an octopus cluster, but I expect this to be an issue with any other setup as well.

The Ceph Dashboard will also have functionality limited by this issue, which may not easily be resolvable as SMART data also cannot be read out in virtual machines.

```
➜  ~ ceph device ls
DEVICE HOST:DEV DAEMONS LIFE EXPECTANCY 
➜  ~ udevadm info /dev/vda
P: /devices/pci0000:00/0000:00:03.0/virtio0/block/vda
N: vda
S: disk/by-path/pci-0000:00:03.0
S: disk/by-path/virtio-pci-0000:00:03.0
E: DEVLINKS=/dev/disk/by-path/pci-0000:00:03.0 /dev/disk/by-path/virtio-pci-0000:00:03.0
E: DEVNAME=/dev/vda
E: DEVPATH=/devices/pci0000:00/0000:00:03.0/virtio0/block/vda
E: DEVTYPE=disk
E: ID_PART_TABLE_TYPE=gpt
E: ID_PART_TABLE_UUID=42c809fd-9a5d-4dfe-84b2-6d931bf350bf
E: ID_PATH=pci-0000:00:03.0
E: ID_PATH_TAG=pci-0000_00_03_0
E: MAJOR=253
E: MINOR=0
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=5101428
```

Adding device information for VMs might resolve the problem for Ceph creating device IDs: https://lists.opensuse.org/opensuse-bugs/2012-04/msg00361.html

**Comment by bk201** [comment]
I can confirm adding serial works, thanks!
