### ISSUE TITLE
ses7 create produces "cephadm_bootstrap/mon_ip: None" when "--libvirt-networks" option is used

### ISSUE THREAD

**Issue by jan--f** [SUSE/sesdev#509]
I pass a pre-created network to sesdev via --libvirt-network. This seems to be disregarded when the bootstrap mon ip is inferred.

**Comment by smithfarm** [comment]
@jan--f It's pretty obvious why this is happening. Here is the code in question:

```
 23             if self.settings.libvirt_networks:
 22                 for network in self.settings.libvirt_networks.split(','):
 21                     networks += (
 20                         'node.vm.network :private_network,'
 19                         ':forward_mode => "route", :libvirt__network_name'
 18                         '=> "{}"\n').format(network)
 17             else:
 16                 if 'master' in node_roles or 'suma' in node_roles:
 15                     public_address = '{}{}'.format(self.settings.public_network, 200)
 14                     networks = ('node.vm.network :private_network, autostart: true, ip:'
 13                                 '"{}"').format(public_address)
 12                 else:
 11                     public_address = '{}{}'.format(self.settings.public_network, 200 + node_id)
 10                     networks = ('node.vm.network :private_network, autostart: true, ip:'
  9                                 '"{}"').format(public_address)
  8                 networks = ('node.vm.network :private_network, autostart: true, ip:'
  7                             '"{}"').format(public_address)
  6                 if self.settings.ipv6:
  5                     networks += ', libvirt__guest_ipv6: "yes"' \
  4                                 ', libvirt__ipv6_address: "fde4:8dba:82e1::c4"' \
  3                                 ', libvirt__ipv6_prefix: "64"'
  2 
  1             if 'bootstrap' in node_roles:
  0                 self.bootstrap_mon_ip = public_address
```

In the `self.settings.libvirt_networks == True` code path, `public_address` is not set. Do you have any idea how, in this code path, we could programatically determine the IP address that libvirt will assign to the bootstrap VM? Note that this is running before the VM is actually created.

**Comment by jan--f** [comment]
Agreed, the cause is quite obvious. Testing if ceph-salt can just handle that now, by only passing `bootstrap_mon_ip` if its not `None`. Will report back.

**Comment by smithfarm** [comment]
@jan--f If it works now, it probably won't work in the future. See https://github.com/ceph/ceph-salt/issues/406

**Comment by jan--f** [comment]
sigh..well for ceph-salt this is fair. However we need to then make "more real world" deployments (namely dhcp provided ip addresses) a first class citizen in sesdev.

Fwiw the approach above works fine. I'll look into sesdev choosing an address then.

**Comment by smithfarm** [comment]
> Fwiw the approach above works fine. I'll look into sesdev choosing an address then.

OK. The provisioner (everything under `seslib/templates/salt/ceph-salt`) runs after the VMs get created, so it can see the IP addresses. You could put a `{% if bootstrap_mon_ip is None %}` conditional block in there.
