### ISSUE TITLE
image_paths override in config.yaml broken since introduction of image_paths_{product,devel}

### ISSUE THREAD

**Issue by tserong** [SUSE/sesdev#563]
https://github.com/SUSE/sesdev/pull/561 replaced `image_paths` in settings.py with `image_paths_product` and `image_paths_devel`. Likewise `Constant.IMAGE_PATHS` became `Constant.IMAGE_PATHS_PRODUCT` and `Constant.IMAGE_PATHS_DEVEL`. However, `Settings._load_config_file` still uses `image_paths` and `Constant.IMAGE_PATHS`:
https://github.com/SUSE/sesdev/blob/f9201cab5b72b66e383a5dbcf7b7636328cc8eae/seslib/settings.py#L434
i.e. the override in config.yaml is still expected to only be `image_paths`. This causes `sesdev create` to fail with:

```
...
    __fill_in_config_tree('image_paths', Constant.IMAGE_PATHS)
AttributeError: type object 'Constant' has no attribute 'IMAGE_PATHS'
```

The easy fix is:

```diff --git a/seslib/settings.py b/seslib/settings.py
index 216b6da..d7a9b48 100644
--- a/seslib/settings.py
+++ b/seslib/settings.py
@@ -431,7 +431,8 @@ class Settings():
         assert isinstance(config_tree, dict), "yaml.load() of config file misbehaved!"
         __fill_in_config_tree('os_repos', Constant.OS_REPOS)
         __fill_in_config_tree('version_devel_repos', Constant.VERSION_DEVEL_REPOS)
-        __fill_in_config_tree('image_paths', Constant.IMAGE_PATHS)
+        __fill_in_config_tree('image_paths_devel', Constant.IMAGE_PATHS_DEVEL)
+        __fill_in_config_tree('image_paths_product', Constant.IMAGE_PATHS_PRODUCT)
         __fill_in_config_tree('version_default_roles', Constant.ROLES_DEFAULT_BY_VERSION)
         return config_tree

```

I was going to submit a PR with that, but then realised README.md has a bunch of example config.yaml files using the old `image_paths` form, and I wanted to check first to make sure this was the correct approach, before rewriting those examples too.

**Comment by smithfarm** [comment]
So, yeah, it looks like #561 did "omit" (run roughshod over?) the necessary changes to the `__fill_in_config_tree` calls and `README.md`. I don't think you're missing anything.
