### ISSUE TITLE
sesdev lets the user try to remove a box that is in use by a deployment

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#619]
In a situation where deployments exist that are using the `leap-15.3` box, sesdev lets us remove it - or, rather, try to. Vagrant refuses to remove the box, but sesdev doesn't expose to the user what Vagrant says when sesdev does `vagrant box remove ...` on the box.

From the user's perspective, the command simply hangs in this case:

```
(venv) smithfarm@geras:~/sesdev> sesdev box remove leap-15.3
You have asked to remove the following Vagrant Box
--------------------------------------------------
opensuse/Leap-15.3.x86_64

Do you really want to remove 1 Vagrant Box [Y/n]: y
^C^C
Aborted!
```

**Comment by asettle** [comment]
@m-ildefons could you test this behaviour too, please? :)
