### ISSUE TITLE
pacific deployments end in "HEALTH_WARN 1 failed cephadm daemon(s): daemon node-exporter.master on master is in error state"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#620]
Reproducer:

```
$ sesdev create pacific --single-node
```

Symptom of bug:

The deployment completes successfully, but the system is in HEALTH_WARN. 

`ceph health detail` reports:

```
master:~ # ceph health detail
HEALTH_WARN 1 failed cephadm daemon(s)
[WRN] CEPHADM_FAILED_DAEMON: 1 failed cephadm daemon(s)
    daemon node-exporter.master on master is in error state
```

**Comment by smithfarm** [comment]
When I run a default 4-node pacific deployment, I get node-exporter failures on multiple nodes:

```
master:~ # ceph health detail
HEALTH_WARN 2 failed cephadm daemon(s); too many PGs per OSD (257 > max 250)
[WRN] CEPHADM_FAILED_DAEMON: 2 failed cephadm daemon(s)
    daemon node-exporter.master on master is in error state
    daemon node-exporter.node1 on node1 is in unknown state
```

**Comment by p-se** [comment]
The container image is not reachable from the SUSE registry at this point in time. I do not know why that is, but I'm investigating. Alternatively, an upstream container image for Node-Exporter could be used, to work around that issue.

**Comment by smithfarm** [comment]
Another possible fix we're looking at: https://github.com/SUSE/ceph/pull/445

**Comment by smithfarm** [comment]
It sounds like we need to look at getting the monitoring containers we use "persisted" - i.e. ensuring that they don't get dropped when a newer version of the container gets pushed to the registry.

**Comment by p-se** [comment]
Issue was resolved. The container did not disappear, but due to an in a merge conflict resolution in downstream Ceph, we've had an older path to a container image configured, that was not available anymore.
