### ISSUE TITLE
SES7p is showing "Please expand your cluster first" on dashboard

### ISSUE THREAD

**Issue by s0nea** [SUSE/sesdev#624]
I'm not really sure if it's an actual issue. I just want to report that a new deployment of an SES7p cluster is showing "Please expand your cluster first" on the dashboard page:

![Screenshot_2022-01-18_10-00-33](https://user-images.githubusercontent.com/8761082/149904912-55c6d7b4-cb52-4ab0-882a-9b960f472863.png)

If this is the desired behavior, please just close the issue.

**Comment by votdev** [comment]
To get rid of this the command `ceph config-key set "mgr/dashboard/cluster/status" "POST_INSTALLED"` needs to be executed during/after deployment.

**Comment by p-se** [comment]
Not a big deal for sesdev, though I wonder where we'd call the command downstream. And if we decided to solve it downstream, there may not be anything left to do for sesdev.

**Comment by tserong** [comment]
This thing also appears on clusters that were upgraded from earlier versions of ceph, which have plenty of hosts and OSDs. IMO this should be an upstream ceph bug/issue, to detect that there _is_ a running cluster, and not show that screen in that case.

**Comment by tserong** [comment]
I've opened https://tracker.ceph.com/issues/54215 for this

**Comment by votdev** [comment]
The associated upstream PR is https://github.com/ceph/ceph/pull/44951.

**Comment by votdev** [comment]
Branding issue will be fixed by https://github.com/SUSE/ceph/pull/450
