### ISSUE TITLE
ses7p deployment with `--product` not successful

### ISSUE THREAD

**Issue by s0nea** [SUSE/sesdev#648]
The `sesdev create ses7p --single-node ses7p-mini --product` deployment is failing with:

```
master: 1 of 1 minions have submitted their keys.
    master: ++ salt-key -Ay
    master: The following keys are going to be accepted:
    master: Unaccepted Keys:
    master: master.ses7p-mini.test
    master: Key for minion master.ses7p-mini.test accepted.
    master: Pinging 1 minions...
    master: ++ set +x
    master: 0 of 1 minions responded to ping.
    master: ++ sleep 3
    master: Pinging 1 minions...
    master: ++ set +x
    master: 1 of 1 minions responded to ping.
    master: ++ set -ex
    master: ++ zypper --non-interactive install ceph-salt
    master: Loading repository data...
    master: Reading installed packages...
    master: 'ceph-salt' not found in package names. Trying capabilities.
    master: No provider of 'ceph-salt' found.
    master: +++ err_report 505
    master: +++ local hn
    master: +++ set +x
    master: Error in provisioner script trapped!
    master: => hostname: master
    master: => script: /tmp/vagrant-shell
    master: => line number: 505
    master: Bailing out!
```

Without the `--product` option everything is fine.

If this is on purpose just close the issue, please.

**Comment by tserong** [comment]
`--product` is meant to work. From the error above ("No provider of 'ceph-salt' found"), it looks like you're missing the storage repo. At some point in the past, the SES7.1 repos were commented out. This was fixed by https://github.com/SUSE/sesdev/pull/645, so my guess is you didn't have that fix yet when you hit this problem.

**Comment by m-ildefons** [comment]
I failed to reproduce this on the latest checkout of master.
You'll need to dig into your environment if this is still a problem for you. Otherwise I think this issue can be closed.

**Comment by s0nea** [comment]
Thank you both for your answers. This error doesn't appear to me anymore. Closing the issue. Thanks again!
