### ISSUE TITLE
"sesdev create" sometimes hangs

### ISSUE THREAD

**Issue by rjfd** [SUSE/sesdev#67]
Sometimes when during the provision phase of `vagrant up` (ran by `sesdev create`) when some bash command fails (probably returning a `retcode != 0`) sesdev does not return to the shell keeps running without doing nothing.

Last time it happened was when running the following configuration:

```
sesdev create octopus --roles="[admin],[mon,mgr,storage],[mon,mgr,storage],[mon,mgr,storage]" --ram=2 --qa-test test
```

**Comment by smithfarm** [comment]
@rjfd The issue would seem to be transient, because I failed to reproduce. 

Command I used:

`sesdev create octopus --roles="[admin],[mon,mgr,storage],[mon,mgr,storage],[mon,mgr,storage]" --ram=2 --ceph-bootstrap-repo https://github.com/SUSE/ceph-bootstrap.git --ceph-bootstrap-branch master --ceph-container-image registry.opensuse.org/filesystems/ceph/master/upstream/images/ceph/ceph --qa-test octopus_test1`

Last screen of output:

```
    admin: WWWW: ceph_health_test
    admin: + set +x
    admin: + ceph status
    admin:   cluster:
    admin:     id:     be09d766-42d5-11ea-bbb8-52540088717e
    admin:     health: HEALTH_WARN
    admin:             3 stray host(s) with 10 service(s) not managed by cephadm
    admin:  
    admin:   services:
    admin:     mon: 3 daemons, quorum node1.octopus_test1.com,node2,node3 (age 78s)
    admin:     mgr: hwboak(active, since 103s), standbys: icdsnv, ytvgxh
    admin:     osd: 6 osds: 6 up (since 13s), 6 in (since 13s)
    admin:  
    admin:   data:
    admin:     pools:   0 pools, 0 pgs
    admin:     objects: 0 objects, 0 B
    admin:     usage:   6.0 GiB used, 42 GiB / 48 GiB avail
    admin:     pgs:     
    admin:  
    admin: ++ ceph health detail --format json
    admin: ++ jq -r .status
    admin: 60-second grace period
    admin: + cluster_status=HEALTH_WARN
    admin: + set +x
    admin: Failed to reach HEALTH_OK even after waiting for 5 minutes
    admin: 
    admin: Overall result: NOT_OK (error )
Command '['vagrant', 'up']' failed: ret=1 stderr:
b"==> admin: An error occurred. The error will be shown after all tasks complete.\nAn error occurred while executing multiple actions in parallel.\nAny errors that occurred are shown below.\n\nAn error occurred while executing the action on the 'admin'\nmachine. Please handle this error then try again:\n\nThe SSH command responded with a non-zero exit status. Vagrant\nassumes that this means the command failed. The output for this command\nshould be in the log above. Please read the output to determine what\nwent wrong.\n"
```

**Comment by smithfarm** [comment]
The question is: does "vagrant up" really return to sesdev, which hangs, or does "vagrant up" hang? And why does it hang sometimes and other times not?

**Comment by rjfd** [comment]
> The question is: does "vagrant up" really return to sesdev, which hangs, or does "vagrant up" hang? And why does it hang sometimes and other times not?

I don't know, I couldn't figure out which one hangs.

> 
> @rjfd How long did you let it hang before giving up?

Not sure, probably just a few minutes.

**Comment by smithfarm** [comment]
Can't reproduce
