### ISSUE TITLE
Support for Ceph on K8s

### ISSUE THREAD

**Issue by jan--f** [SUSE/sesdev#7]
Without diving into details, it looks like adding support for rook deployments shouldn't be too hard to add...?

**Comment by rjfd** [comment]
I agree. The plan is to follow the instructions described here: https://en.opensuse.org/openSUSE:Ceph

**Comment by capri1989** [comment]
https://github.com/SUSE/sesdev/pull/103

**Comment by smithfarm** [comment]
https://github.com/SUSE/sesdev/pull/103 merged
