### ISSUE TITLE
feature request: documented way to transfer file from guest to host

### ISSUE THREAD

**Issue by smithfarm** [SUSE/sesdev#91]
Use case:

I need to copy a file (e.g. `/var/log/ceph-bootstrap.log`) from a guest VM to the host. 

The existing documentation does not mention this anywhere, and I have no idea how to achieve it. Ordinarily I would try to run `vagrant port` to find out which port on the host the guest's SSH daemon is listening on, but this doesn't work:

```
$ cd ~/.vagrant.d/boxes/sles-15-sp2/0/libvirt
$ vagrant port
The libvirt provider does not support listing forwarded ports. This is
most likely a limitation of the provider and not a bug in Vagrant. If you
believe this is a bug in Vagrant, please search existing issues before
opening a new one.
```

Also, the synced directory `/vagrant` appears to be unidirectional: i.e. when the guest VM is created, `/vagrant` is populated from the host via rsync, but changes made by the guest to this directory are not reflected on the host (?).

**Comment by smithfarm** [comment]
https://www.alexkras.com/how-to-copy-one-file-from-vagrant-virtual-machine-to-local-host/

Unfortunately, this doesn't work with the libvirt provider.

**Comment by LenzGr** [comment]
Would implementing an `scp` command similar to `sesdev ssh` be an acceptable solution?

**Comment by rjfd** [comment]
> Would implementing an `scp` command similar to `sesdev ssh` be an acceptable solution?

That would be cool!

**Comment by smithfarm** [comment]
@LenzGr I've been thinking about it, and I believe it's feasible!

**Comment by LenzGr** [comment]
Thank you for you implementing `sesdev scp`, @smithfarm
