### ISSUE TITLE
README: add "Installation on Ubuntu" section that mentions "sudo apt install libvirt-dev"

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/sesdev#96]
minor nit: 

libvirt-devel is called `libvirt-dev` on debian/ubuntu. Would be nice to add this to the README

**Comment by smithfarm** [comment]
It would be nice to add an entire "Installation on Ubuntu" section to the README...

**Comment by sebastian-philipp** [comment]
well, it already works perfectly on ubuntu as well.
